import Itens.armamentos.armaduras
import Itens.armamentos.ferramentas.arcos
import Itens.armamentos.ferramentas.espadas
import Itens.armamentos.ferramentas.picaretas
import Itens.armamentos.ferramentas.machados
import Itens.armamentos.roupas
import Itens.maleficos.comidas
import Itens.maleficos.venenos
import Itens.itens